---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ismoh-PC.
--- DateTime: 17.07.2022 17:25
---

--local fu       = require("file_util")
--profiler = require("profiler")
--
--local gRequire = _G.require
--
--_G.require     = function(name)
--    profiler.start()
--    local required = gRequire(name)
--    profiler.stop()
--    return required
--end

--function wrap(f)
--    return function(...)
--        start()
--        local r = {f(...)}
--        stop()
--        return (table.unpack or unpack)(r)
--    end
--end
--
--for k, v in pairs(lib) do
--    if type(v) == 'function' then lib[k] = wrap(v) end
--end

--[[
Ordered table iterator, allow to iterate on the natural order of the keys of a
table.

Example:
]]

function __genOrderedIndex( t )
    local orderedIndex = {}
    for key in pairs(t) do
        table.insert( orderedIndex, key )
    end
    table.sort( orderedIndex )
    return orderedIndex
end

function orderedNext(t, state)
    -- Equivalent of the next function, but returns the keys in the alphabetic
    -- order. We use a temporary ordered key table that is stored in the
    -- table being iterated.

    local key = nil
    --print("orderedNext: state = "..tostring(state) )
    if state == nil then
        -- the first time, generate the index
        t.__orderedIndex = __genOrderedIndex( t )
        key = t.__orderedIndex[1]
    else
        -- fetch the next value
        for i = 1,table.getn(t.__orderedIndex) do
            if t.__orderedIndex[i] == state then
                key = t.__orderedIndex[i+1]
            end
        end
    end

    if key then
        return key, t[key]
    end

    -- no more value to return, cleanup
    t.__orderedIndex = nil
    return
end

function orderedPairs(t)
    -- Equivalent of the pairs() function on tables. Allows to iterate
    -- in order
    return orderedNext, t, nil
end