echo off

echo "----------------------------------------------------------------------------------------------------------------------"
echo "This script will install LuaRocks for NoitaMP without destroying your (maybe) already installed LuaRocks installation!"

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Backing up users config-5.1.lua and default-lua-version.lua if they exist"
if not exist %1 mkdir %1
if exist %1\config-5.1.lua move %1\config-5.1.lua %1\config-5.1.lua.bak
if exist %1\default-lua-version.lua move %1\default-lua-version.lua %1\default-lua-version.lua.bak

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Creating config-5.1.lua and default-lua-version.lua for NoitaMP"
%2\.building\luarocks-3.9.1-windows-32\luarocks.exe config --lua-version="5.1" --local lua_dir %2\LuaJIT-2.1.0-beta3

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Init LuaRocks project for NoitaMP"
%2\.building\luarocks-3.9.1-windows-32\luarocks.exe --lua-version="5.1" init noita-mp --output="%2\mods\noita-mp" --homepage="https://github.com/Ismoh/NoitaMP" --license="GNU GPL v3"
%2\.building\luarocks-3.9.1-windows-32\luarocks.exe config --scope project variables.LUA_DIR %2\LuaJIT-2.1.0-beta3
%2\.building\luarocks-3.9.1-windows-32\luarocks.exe config --scope project variables.LUA_BINDIR %2\LuaJIT-2.1.0-beta3\bin
%2\.building\luarocks-3.9.1-windows-32\luarocks.exe config --scope project variables.LUA_INCDIR %2\LuaJIT-2.1.0-beta3\include
%2\.building\luarocks-3.9.1-windows-32\luarocks.exe config --scope project variables.LUA_LIBDIR %2\LuaJIT-2.1.0-beta3\lib

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Small cleanup of unnecessary files generated by LuaRocks"
del %2\mods\noita-mp\.gitignore

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Reverting users config-5.1.lua and default-lua-version.lua"
if exist %1\config-5.1.lua.bak (move %1\config-5.1.lua.bak %1\config-5.1.lua) else (del %1\config-5.1.lua)
if exist %1\default-lua-version.lua.bak (move %1\default-lua-version.lua.bak %1\default-lua-version.lua) else (del %1\default-lua-version.lua)

echo "----------------------------------------------------------------------------------------------------------------------"
echo "Done! You can now use LuaRocks for NoitaMP!"
