name: Deploy mkdocs
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    name: 'Deploy mkdocs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - name: Mirror GitHub md's
        run: |
          cp -f CONTRIBUTING.md docs/contributing/CONTRIBUTING.md
          cp -f CODE_OF_CONDUCT.md docs/contributing/CODE_OF_CONDUCT.md
          cp -f LICENSE.md docs/about/LICENSE.md
          cp -f SUPPORT.md docs/SUPPORT.md
      - run: mkdocs gh-deploy --force
  
